### ISSUE TITLE
Fix import from holidays

### ISSUE THREAD

**Issue by vcapretz** [bukinoshita/holiday#4]
Currently the import is this way 
`const holidays = require('./holidays/2017')`

we need to change it so it imports the file from the current year (or for future implementations, past years)

I'm going to work on this and send the PR

**Comment by vcapretz** [comment]
hey @bukinoshita here's what I thought: 

- folder holidays could have a `index.js` to export all years, like this: 
```
'use strict'

module.exports = {2017: require('./2017')}
```

- function `holiday` must receive an Object as a parameter instead of multiple vars, this way is easier for us to add/remove parameters and also don't care about their order. 

- _optional_ all parameters would have a default value in case values are not sent to `holiday` function:
  - year: current year
  - month: current month
  - day: current day
  - country: 'us'

let me know what you think, after this huge change I could prepare `is-holiday` as well

**Comment by bukinoshita** [comment]
Awesome @vcapretz ! Sounds great to me!
